### PR TITLE
Fix Console Error and add setting icon button tips

### PR DESCRIPTION
**Pull request by lumosxin**
Fix the Console error when the network error occurs, prompting that `Cannot read properties of undefined (reading 'data')`, undefined code `data` in `error.response` and add a setting icon button prompt.

### CODE REVIEW

**Comment by lumosxin** [comment]
@microsoft-github-policy-service agree

**Comment by tricktreat** [comment]
Already fixed. Thanks!

**Comment by lumosxin** [comment]
> Already fixed. Thanks!

Have my commit any error, this pull requests have closed and go and modify the same thing in
https://github.com/microsoft/JARVIS/commit/0551cc185a01e9821e810b184599579f1b251835#diff-36fc287db2658d58a7b32df978e4503ffac9aa72332916823fdf8abba07697a3
and
https://github.com/microsoft/JARVIS/commit/0551cc185a01e9821e810b184599579f1b251835#diff-affec23b9cda8e238570dd4de9b7edd5f96158215f2c000e9933169ed92b349c
As an open source, i just want to keep contributing, Thanks!

**Comment by lumosxin** [comment]
> Already fixed. Thanks!

Have my commit any error, this pull requests have closed and go and modify the same thing in
https://github.com/microsoft/JARVIS/commit/0551cc185a01e9821e810b184599579f1b251835#diff-36fc287db2658d58a7b32df978e4503ffac9aa72332916823fdf8abba07697a3
and
https://github.com/microsoft/JARVIS/commit/0551cc185a01e9821e810b184599579f1b251835#diff-affec23b9cda8e238570dd4de9b7edd5f96158215f2c000e9933169ed92b349c
Have anything different

**Comment by lumosxin** [comment]
Have [my commit](https://github.com/microsoft/JARVIS/pull/71/files) any error, this pull requests have closed and go and modify the same thing in [your commit](https://github.com/microsoft/JARVIS/commit/0551cc185a01e9821e810b184599579f1b251835#diff-36fc287db2658d58a7b32df978e4503ffac9aa72332916823fdf8abba07697a3) and
[your commit](https://github.com/microsoft/JARVIS/commit/0551cc185a01e9821e810b184599579f1b251835#diff-affec23b9cda8e238570dd4de9b7edd5f96158215f2c000e9933169ed92b349c), Has anything difference

**Comment by lumosxin** [comment]
Have [my commit](https://github.com/microsoft/JARVIS/pull/71/files) any error, this pull requests have closed and go and modify the same thing in [your commit](https://github.com/microsoft/JARVIS/commit/0551cc185a01e9821e810b184599579f1b251835#diff-36fc287db2658d58a7b32df978e4503ffac9aa72332916823fdf8abba07697a3) and
[your commit](https://github.com/microsoft/JARVIS/commit/0551cc185a01e9821e810b184599579f1b251835#diff-affec23b9cda8e238570dd4de9b7edd5f96158215f2c000e9933169ed92b349c), Has anything difference

**Pull request closed without merging**
