### PR TITLE
add general prompt flow diagram for ease of understanding

### PR DESCRIPTION
**Pull request by Toubat**

### CODE REVIEW

**Comment by tricktreat** [comment]
Thanks for your efforts, it is very helpful.

**Comment by tricktreat** [comment]
@Toubat Hi. Could you please provide the editable source file? I need to make some changes to embed it in the README.

**Comment by Toubat** [comment]
> @Toubat Hi. Could you please provide the editable source file? I need to make some changes to embed it in the README. You can email it to [itricktreat@gmail.com](mailto:itricktreat@gmail.com). Thanks!

@tricktreat Hi. I have sended you the source. Can you open it?

**Comment by tricktreat** [comment]
@Toubat I have received it and can open it well. Thanks again.

**Pull request merged**
